# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    #transport: smtp
    #username: devweb@pmsg.rj.gov.br
    #password: dev@#web2018
    #host: 172.17.1.222
    transport: smtp
    username: madtbr@gmail.com
    password: TREm@#2017!
    host: smtp.gmail.com
    encryption: ssl
    port: 465
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false